# Jekyll Configuration
safe: true
source: .
destination: _site
lsi: false
keep_files:  ['.git','.svn', '.less']
markdown: rdiscount
pygments: true
permalink: pretty
baseurl: "http://citisent.github.io/kane/"


# Project Settings
project:
    name: Kane
