# Jekyll Configuration
safe: true
source: .
destination: _site
lsi: false
markdown: rdiscount
pygments: true
permalink: pretty
baseurl: "http://citisent.github.io/cs-gui/"

project:
    name: CitiSent GUI
