# Jekyll Configuration
safe: true
source: .
destination: _site
lsi: false
markdown: rdiscount
pygments: true
permalink: pretty
baseurl: "http://citisent.github.io/kane"
exclude: ['*.less']
pygments: false
relative_permalinks: true

# Project Settings
project:
    name: Kane
